---
name: sss-bosh-deployment

releases:
- name: sss-app-release-blobs
  version: "latest"

stemcells:
- alias: ubuntu-jammy
  os: ubuntu-jammy
  version: "latest"

update:
  canaries: 1
  canary_watch_time: 15000-30000
  max_in_flight: 1
  serial: true
  update_watch_time: 15000-300000

instance_groups:
- name: rubyapp
  instances: 1
  azs: [z1, z2]
  jobs:
  - name: rubyapp
    release: sss-app-release-blobs
  vm_type: small
  stemcell: ubuntu-jammy
  networks:
  - name: default

  persistent_disk_type: medium